// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aoobqkszmxperksubwpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvb2Jxa3N6bXhwZXJrc3Vid3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNDI3NjAsImV4cCI6MjA3MTkxODc2MH0.okv4Rokj05J-M7wSYLiuYIyRfG2rX5OBLAvB_D76c60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});